x = ( 1, 2, 3, 4, 5)
y = len(x)
z = list(reversed(x))
n = (0, 0, 0, 0, 0, 1)
o = ( 6, 7, 8 )
p = zip(x, o)
q = ('wizard', 'fighter', 'thief')
for i, v in enumerate(q): print(f'{i}: {v}')
for a, b in p: print(f'{a} - {b}')
print(x)
print(z)
print(y)
for i in z: print(i)
print(sum(x))
print(sum(x, 9))
print(any(n))
print(all(x))